#!groovy

// Generated by IBM TransformationAdvisor
// Tue Nov 26 14:36:53 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}