#!groovy

// Generated by IBM TransformationAdvisor
// Mon Nov 25 20:08:00 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}